# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  docker-agents: patrickmcfadden/docker-agent@dev:first

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - docker-agents/publish:
          image: pmcfadden/java-vertx-demo
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
