---

kind: Service
apiVersion: v1
metadata:
  name: java-demo
spec:
  selector:
    app: java-demo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-deployment
  labels:
    app: java-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
      - name: java-vertx-demo
        image: quay.io/pmcfadden/java-vertx-demo:0.1.9
        ports:
        - containerPort: 8080
